import Link from 'next/link';
import prisma from '@/lib/prisma';
import { clubOfficialWhere, discoverySelect } from '@/lib/fan-discovery-data';
import { evidence, isConfirmedFixture } from '@/lib/fan-discovery';
import MatchFactShare from '@/components/MatchFactShare';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'מרכז יום משחק | StatsAI' };
export default async function MatchdayPage() {
  const now = new Date();
  const candidates = await prisma.game.findMany({ where: { AND: [clubOfficialWhere, { OR: [{ status: 'ONGOING', dateTime: { gte: new Date(now.getTime() - 12 * 3600000) } }, { status: 'SCHEDULED', dateTime: { gte: now } }] }] }, select: discoverySelect, orderBy: { dateTime: 'asc' } });
  const game = candidates.find(g => g.status === 'ONGOING' && isConfirmedFixture(g)) || candidates.find(isConfirmedFixture) || await prisma.game.findFirst({ where: { AND: [clubOfficialWhere, { status: 'COMPLETED', dateTime: { lte: now }, homeScore: { gte: 0 }, awayScore: { gte: 0 } }] }, select: discoverySelect, orderBy: { dateTime: 'desc' } });
  const opponent = game ? (game.homeTeam.apiFootballId === 563 ? game.awayTeam : game.homeTeam) : null;
  // Seasonal team IDs differ; stable provider identity finds the actual past meeting.
  const previous = game && opponent?.apiFootballId ? await prisma.game.findFirst({ where: { AND: [clubOfficialWhere, { status: 'COMPLETED', id: { not: game.id }, dateTime: { lt: game.dateTime }, homeScore: { gte: 0 }, awayScore: { gte: 0 }, OR: [{ homeTeam: { apiFootballId: opponent.apiFootballId } }, { awayTeam: { apiFootballId: opponent.apiFootballId } }] }] }, select: discoverySelect, orderBy: { dateTime: 'desc' } }) : null;
  const past = previous ? evidence(previous) : null;
  const fact = game ? evidence(game) : null;
  return <main dir="rtl" className="mx-auto max-w-4xl space-y-6 px-4 py-10"><Link href="/club" className="underline">חזרה למועדון</Link><h1 className="text-3xl font-black">מרכז יום משחק</h1>{game ? <><section className="space-y-4 rounded-2xl border bg-white p-6"><p className="font-bold text-red-800">{game.status === 'ONGOING' ? 'המשחק החי' : game.status === 'SCHEDULED' ? 'המשחק הבא' : 'המשחק האחרון עם תוצאה'}</p><h2 className="text-2xl font-black">{game.homeTeam.nameHe || game.homeTeam.nameEn} — {game.awayTeam.nameHe || game.awayTeam.nameEn}</h2><p>{new Intl.DateTimeFormat('he-IL', { timeZone: 'Asia/Jerusalem', dateStyle: 'long', ...(game.status !== 'COMPLETED' ? { timeStyle: 'short' as const } : {}) }).format(game.dateTime)} · {game.season.name} · {game.competition?.nameHe || game.competition?.nameEn}</p>{fact && <p>{fact.result} · {fact.goalsFor} שערי זכות, {fact.goalsAgainst} שערי חובה</p>}<nav className="flex flex-wrap gap-4" aria-label="פרטי המשחק">{[['overview', 'הכנה למשחק וזמינות הסגל'], ['lineups', 'הרכבים'], ['stats', 'סטטיסטיקה']].map(([tab, label]) => <Link key={tab} href={`/games/${game.id}?view=premier&tab=${tab}`} className="underline">{label}</Link>)}</nav><p className="text-sm text-stone-600">הזמינות תלויה במקורות המשחק. משחקים עם שעה לא מאושרת אינם מוצגים כמשחק הבא. אין כאן קביעה לגבי שיאים כשכיסוי הנתונים אינו מלא.</p>{fact && <MatchFactShare fact={fact} />}</section><section className="space-y-3 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">מפגש קודם מהארכיון</h2>{past ? <><p>{new Date(past.date).toLocaleDateString('he-IL', { timeZone: 'Asia/Jerusalem' })} · עונת {past.season} · {past.competition}</p><p>{past.result} מול {past.opponent}: {past.goalsFor} שערי זכות, {past.goalsAgainst} שערי חובה.</p><a href={past.source} className="block underline">למשחק ולמקור הנתון</a><p className="text-sm text-stone-600">ללא הכרעת פנדלים. המפגש האחרון עם תוצאה ידועה שנמצא באתר; ייתכן שהארכיון חלקי.</p><MatchFactShare fact={past} /></> : <p>לא נמצא מפגש קודם מזוהה עם תוצאה ידועה במאגר.</p>}</section></> : <p>אין כרגע משחק מזוהה עם מועד מאושר או תוצאה ידועה.</p>}</main>;
}
